#!/usr/bin/env bash

set -euo pipefail

source $(dirname ${BASH_SOURCE[0]})/utils/all.sh

out "Running pre-commit hook"

if [[ $(git diff --name-status $current_branch $main_branch -- ./terraform/) ]]; then
    cd terraform
    out "Formatting terraform files"
    terraform fmt
    out "Validating terraform files"
    terraform validate
    cd ..
fi

exit 0
